region           = "eu-west-2"
env              = "prod"
name_prefix      = "cosight"
tf_state_bucket  = "cosight-healthlake-tfstate-prod"
tf_lock_table    = "tf-state-lock"
logs_bucket_name = "cosight-healthlake-logs-prod"